"use client";

import { useState, useEffect, useCallback, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { cn } from "@/lib/utils";
import { WidgetCard } from "@/components/admin/widget-card";
import { KeywordTargetEditor } from "@/components/admin/widgets/keyword-target-editor";
import { SubscriberActions } from "@/components/admin/widgets/subscriber-actions";
import { BrokenLinkPipeline } from "@/components/admin/widgets/broken-link-pipeline";

const TABS = [
  { id: "traffic", label: "Traffic" },
  { id: "keywords", label: "Keywords" },
  { id: "subscribers", label: "Subscribers" },
  { id: "distribution", label: "Distribution" },
  { id: "competitors", label: "Competitors" },
];

interface Competitor {
  id: string;
  name: string;
  url: string;
  active: boolean;
}

interface SubscriberStats {
  active: number;
  inactive: number;
  newThisWeek: number;
}

function GrowthPageInner() {
  const searchParams = useSearchParams();
  const initialTab = searchParams.get("tab") || "traffic";
  const [activeTab, setActiveTab] = useState(initialTab);
  const [competitors, setCompetitors] = useState<Competitor[]>([]);
  const [subStats, setSubStats] = useState<SubscriberStats>({ active: 0, inactive: 0, newThisWeek: 0 });
  const [balance, setBalance] = useState<{ balance: number; totalSpent: number } | null>(null);
  const [scanning, setScanning] = useState<string | null>(null);

  const fetchCompetitors = useCallback(async () => {
    try {
      const res = await fetch("/api/competitors");
      if (res.ok) {
        const data = await res.json();
        setCompetitors(data.competitors || []);
      }
    } catch { /* silent */ }
  }, []);

  const fetchBalance = useCallback(async () => {
    try {
      const res = await fetch("/api/seo/balance");
      if (res.ok) setBalance(await res.json());
    } catch { /* silent */ }
  }, []);

  useEffect(() => {
    fetchCompetitors();
    fetchBalance();
  }, [fetchCompetitors, fetchBalance]);

  const scanCompetitor = async (id: string) => {
    setScanning(id);
    try {
      await fetch("/api/competitors/scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ competitorId: id }),
      });
    } catch { /* silent */ }
    finally { setScanning(null); }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-display-lg text-text-primary">Growth</h1>
        <p className="text-body-sm text-text-muted mt-1">Traffic, SEO, subscribers, outreach, and competitors.</p>
      </div>

      {/* Tab bar */}
      <div className="flex gap-1 border-b border-border-ghost overflow-x-auto scrollbar-hide">
        {TABS.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={cn(
              "px-4 py-2.5 text-body-sm font-medium transition-colors -mb-px whitespace-nowrap",
              activeTab === tab.id
                ? "text-accent border-b-2 border-accent"
                : "text-text-muted hover:text-text-secondary"
            )}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Traffic tab */}
      {activeTab === "traffic" && (
        <WidgetCard title="Traffic Analytics">
          <div className="py-8 text-center">
            <p className="text-body-md text-text-muted mb-2">
              Traffic data is generated by the Marketing Director agent.
            </p>
            <p className="text-body-sm text-text-muted">
              View the latest report in{" "}
              <span className="text-accent font-mono text-body-xs">pipeline/logs/marketing/</span>
            </p>
          </div>
        </WidgetCard>
      )}

      {/* Keywords tab */}
      {activeTab === "keywords" && (
        <div className="space-y-6">
          {balance && (
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-bg-container border border-border-ghost rounded-lg p-4">
                <p className="font-mono text-caption text-text-muted uppercase tracking-widest mb-1">DataForSEO Balance</p>
                <p className="font-display text-display-sm text-accent">${balance.balance.toFixed(2)}</p>
              </div>
              <div className="bg-bg-container border border-border-ghost rounded-lg p-4">
                <p className="font-mono text-caption text-text-muted uppercase tracking-widest mb-1">Total Spent</p>
                <p className="font-display text-display-sm text-text-primary">${balance.totalSpent.toFixed(2)}</p>
              </div>
            </div>
          )}
          <WidgetCard title="Keyword & Gap Management">
            <KeywordTargetEditor />
          </WidgetCard>
        </div>
      )}

      {/* Subscribers tab */}
      {activeTab === "subscribers" && (
        <div className="space-y-6">
          <WidgetCard title="Subscriber Actions">
            <SubscriberActions />
          </WidgetCard>
        </div>
      )}

      {/* Distribution tab */}
      {activeTab === "distribution" && (
        <div className="space-y-6">
          <WidgetCard title="Broken Link Builder">
            <p className="text-body-xs text-text-muted mb-4">
              Scan competitor sites for broken links, match with your articles, and send outreach emails.
            </p>
            <BrokenLinkPipeline />
          </WidgetCard>
        </div>
      )}

      {/* Competitors tab */}
      {activeTab === "competitors" && (
        <WidgetCard title={`Tracked Competitors (${competitors.length})`}>
          {competitors.length === 0 ? (
            <p className="text-body-sm text-text-muted py-4">No competitors tracked.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-border-ghost">
                    <th className="pb-3 font-mono text-caption text-text-muted uppercase tracking-widest">Name</th>
                    <th className="pb-3 font-mono text-caption text-text-muted uppercase tracking-widest">URL</th>
                    <th className="pb-3 font-mono text-caption text-text-muted uppercase tracking-widest text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border-ghost/50">
                  {competitors.map(c => (
                    <tr key={c.id}>
                      <td className="py-3 text-body-sm text-text-body">{c.name}</td>
                      <td className="py-3 text-body-xs text-accent max-w-[250px] truncate">
                        <a href={c.url} target="_blank" rel="noopener noreferrer">{c.url}</a>
                      </td>
                      <td className="py-3 text-right">
                        <button
                          onClick={() => scanCompetitor(c.id)}
                          disabled={scanning === c.id}
                          className="px-3 py-1 rounded bg-bg-high border border-border-ghost text-body-xs text-text-secondary hover:border-accent hover:text-accent transition-colors disabled:opacity-50"
                        >
                          {scanning === c.id ? "Scanning..." : "Scan"}
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </WidgetCard>
      )}
    </div>
  );
}

export default function GrowthPage() {
  return (
    <Suspense fallback={<div className="text-text-muted p-8">Loading...</div>}>
      <GrowthPageInner />
    </Suspense>
  );
}
