import { cn } from "@/lib/utils";

interface ImageCreditProps {
  photographer?: string;
  photographerUrl?: string;
  source?: string;
  sourceUrl?: string;
  className?: string;
}

// Credit sources that indicate the image was AI-generated by Particle Post.
// We never render a "Photo via ..." line for these — the cover is our own work
// and attributing it as a source is misleading.
const AI_SOURCE_PATTERNS = /^(ai-|generated|gemini|higgsfield)/i;

export function ImageCredit(props: ImageCreditProps) {
  const { photographerUrl, sourceUrl, className } = props;
  // Filter out AI-generated markers regardless of what the frontmatter says
  const photographer =
    props.photographer && !AI_SOURCE_PATTERNS.test(props.photographer)
      ? props.photographer
      : undefined;
  const source =
    props.source && !AI_SOURCE_PATTERNS.test(props.source) ? props.source : undefined;

  if (!photographer && !source) return null;

  return (
    <p className={cn("text-body-xs text-text-muted", className)}>
      Photo{" "}
      {photographer && (
        <>
          by{" "}
          {photographerUrl ? (
            <a
              href={photographerUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-accent transition-colors underline underline-offset-2"
            >
              {photographer}
            </a>
          ) : (
            photographer
          )}
        </>
      )}
      {photographer && source && " on "}
      {source && !photographer && "via "}
      {source &&
        (sourceUrl ? (
          <a
            href={sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-accent transition-colors underline underline-offset-2"
          >
            {source}
          </a>
        ) : (
          source
        ))}
    </p>
  );
}
