name: Deploy Hugo Site

on:
  push:
    branches: ["main"]
    paths:
      - "blog/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN_EXP_21_MAY }}

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo site
        run: hugo --source blog/ --destination ../public/ --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GIT_TOKEN_EXP_21_MAY }}
          publish_dir: ./public
          cname: theparticlepost.com
